# Generated by Django 5.2 on 2025-04-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voted_party',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
