# Generated by Django 5.2 on 2025-04-14 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_voter_voted_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='symbol',
            field=models.ImageField(blank=True, null=True, upload_to='symbols/'),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voted_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.party'),
        ),
    ]
