# Generated by Django 5.2 on 2025-04-14 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_party_symbol_alter_party_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.voter', verbose_name='Voter'),
        ),
    ]
