# Generated by Django 5.2 on 2025-04-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_vote_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecount',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
