# Generated by Django 5.2 on 2025-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_votecount_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voted_party',
            field=models.CharField(default='Unknown', max_length=12),
        ),
    ]
