# Generated by Django 5.2 on 2025-04-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_voter_voted_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='vote_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('gesture', 'Gesture')], default='normal', max_length=10),
        ),
    ]
