# Generated by Django 5.2 on 2025-04-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_voter_vote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_disabled',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('gesture', 'Gesture')], default='N/A', max_length=10),
        ),
    ]
