# Generated by Django 5.1.1 on 2025-04-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_voter_is_disabled_alter_voter_vote_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('gesture', 'Gesture')], default='Gesture', max_length=10),
        ),
    ]
