# Generated by Django 5.1.1 on 2025-04-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_vote_party_symbol_alter_vote_party_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='party_symbol',
        ),
        migrations.AlterField(
            model_name='vote',
            name='party',
            field=models.CharField(max_length=50, verbose_name='Selected Party'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voted_party',
            field=models.CharField(default='Unknown', max_length=12),
        ),
    ]
