# Generated by Django 5.2 on 2025-04-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_remove_vote_party_symbol_alter_vote_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='vote_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Gesture', 'Gesture')], default='Gesture', max_length=10),
        ),
    ]
