# Generated by Django 5.2 on 2025-04-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_alter_voter_vote_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='is_disabled',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote_type',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
