# Generated by Django 5.2 on 2025-04-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_alter_voter_is_disabled_alter_voter_vote_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='party',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.AddField(
            model_name='vote',
            name='Party_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_id',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='is_disabled',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
