# Generated by Django 5.2 on 2025-04-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_remove_vote_party_remove_vote_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='is_disabled',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote_type',
            field=models.CharField(default='Gesture', max_length=50),
        ),
    ]
