# Generated by Django 5.2 on 2025-04-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_alter_voter_is_disabled_alter_voter_vote_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='is_disabled',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='vote_type',
        ),
        migrations.DeleteModel(
            name='VoteCount',
        ),
    ]
